# Generated by Django 3.0 on 2023-11-20 17:06

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231119_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234567', length=10, max_length=20, prefix='cat', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Nice', max_length=100),
        ),
    ]
