# Generated by Django 3.0 on 2023-12-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231206_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cover_image',
            field=models.ImageField(default='seller.jpg', upload_to='user_directory_Path'),
        ),
    ]
